# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMCore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  inhibit_all_warnings!
  # Pods for MVVMCore
  pod 'Alamofire', '~> 4.8.0'
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'

  target 'MVVMCoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
